[flake8]
ignore = D203, W293, W291, E116, W292, E303
exclude =
    # No need to traverse these directories
    .git, .github, .circleci, __pycache__, env, cdk.out, lambdas/a11y_scan, domains, assets, lambda-releases, venv
max-complexity = 10