version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.8.6-node

jobs:

  test:
    executor: default
      
    steps:
      - checkout

      - run:
          name: setup-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      
      - run:
          name: install-deps
          command: |
            pip install -r requirements.txt
      
      - run:
          name: flake8
          command: |
            flake8

      - run:
          name: create-empty-aws-creds
          command: |
            mkdir ~/.aws && touch ~/.aws/credentials
      
      - run:
          name: test
          command: |
            ./cc-test-reporter before-build
            coverage run -m pytest
            coverage xml
            ./cc-test-reporter after-build --debug -t "coverage.py" --exit-code $?

      - store_artifacts: # See circleci.com/docs/2.0/artifacts/ for more details.
          path: coverage.xml
          destination: coverage.xml

  build:
    executor: default

    steps:
      - checkout

      - run:
          name: 'install-cdk'
          command: |
            sudo npm install -g aws-cdk@latest

      - run:
          name: 'build-a11y-scan'
          command: |
            if git diff --name-only master | grep -q 'a11y_scan'; then 
              make build_a11y_scan
            fi

      - run:
          name: 'build-results-joiner'
          command: |
            if git diff --name-only master | grep -q 'results_joiner'; then 
              sudo apt update && sudo apt install -y rsync && make build_results_joiner
            fi
      
      - run:
          name: install-deps
          command: |
            pip install -r requirements.txt

      - run:
          name: 'cdk-diff'
          command: |
            cdk diff 2>&1 | sed -r 's/\\x1B\\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g' || true
      

workflows:
  version: 2
  test-and-build: 
    jobs:
      - test
      - build:
          requires:
            - test


